
package sistema;

import java.sql.Connection;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Clientes extends javax.swing.JFrame {
    ConexionMysql con = new ConexionMysql();
    Connection cn = con.conectar();
    DefaultTableModel model;
    public Clientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        //Icono del JFrame
        setIconImage(new ImageIcon(getClass().getResource("/images/ballet.png")).getImage());
        mostrardatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        containerRegistro = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        boxCompañia = new javax.swing.JComboBox<>();
        containerRegistrar = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        containerActualizar = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        txtnombreMadre = new javax.swing.JTextField();
        txtCuota = new javax.swing.JTextField();
        txtnombrePadre = new javax.swing.JTextField();
        containerbtnInicio = new javax.swing.JPanel();
        btnInicioClient = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatosClientes = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnPorVencer = new javax.swing.JButton();

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/compartimiento.png"))); // NOI18N
        jMenuItem1.setText("Eliminar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALUMNOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Rockwell", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        containerRegistro.setBackground(new java.awt.Color(255, 255, 255));
        containerRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        containerRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                containerRegistroMouseClicked(evt);
            }
        });

        txtId.setBackground(new java.awt.Color(255, 255, 255));
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtId.setEnabled(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(255, 255, 255));
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alumno/a", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });

        txtFecha.setBackground(new java.awt.Color(255, 255, 255));
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Vencimiento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });

        txtTel.setBackground(new java.awt.Color(255, 255, 255));
        txtTel.setForeground(new java.awt.Color(0, 0, 0));
        txtTel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelActionPerformed(evt);
            }
        });
        txtTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelKeyPressed(evt);
            }
        });

        boxCompañia.setBackground(new java.awt.Color(255, 255, 255));
        boxCompañia.setForeground(new java.awt.Color(0, 0, 0));
        boxCompañia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Taller", "Baby Ballet", "Pre Ballet", "Pre Académico", "1er Curso", "2do Curso", "3er Curso", "4to Curso", "5to Curso", "6to Curso", "7mo Curso", "8vo Curso", "Interprete 1", "Interprete 2", "Interprete 3", "Interprete 4", "Admisión ", "Admision 1 y 2 ", "Admision 1, 2 y 3", "Admision Especial" }));
        boxCompañia.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Curso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        boxCompañia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                boxCompañiaKeyPressed(evt);
            }
        });

        containerRegistrar.setBackground(new java.awt.Color(153, 153, 255));

        btnRegistrar.setBackground(new java.awt.Color(0, 51, 51));
        btnRegistrar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registraricon (2).png"))); // NOI18N
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.setIconTextGap(5);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerRegistrarLayout = new javax.swing.GroupLayout(containerRegistrar);
        containerRegistrar.setLayout(containerRegistrarLayout);
        containerRegistrarLayout.setHorizontalGroup(
            containerRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerRegistrarLayout.setVerticalGroup(
            containerRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        containerActualizar.setBackground(new java.awt.Color(153, 153, 255));
        containerActualizar.setForeground(new java.awt.Color(255, 255, 255));

        btnActualizar.setBackground(new java.awt.Color(0, 51, 51));
        btnActualizar.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(0, 0, 0));
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actuIcon (2).png"))); // NOI18N
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setContentAreaFilled(false);
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar.setIconTextGap(5);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerActualizarLayout = new javax.swing.GroupLayout(containerActualizar);
        containerActualizar.setLayout(containerActualizarLayout);
        containerActualizarLayout.setHorizontalGroup(
            containerActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerActualizarLayout.setVerticalGroup(
            containerActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtnombreMadre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombreMadre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombreMadre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre  Madre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtnombreMadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreMadreActionPerformed(evt);
            }
        });
        txtnombreMadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombreMadreKeyPressed(evt);
            }
        });

        txtCuota.setBackground(new java.awt.Color(204, 204, 255));
        txtCuota.setForeground(new java.awt.Color(0, 0, 0));
        txtCuota.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monto Cuota", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuotaActionPerformed(evt);
            }
        });
        txtCuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuotaKeyPressed(evt);
            }
        });

        txtnombrePadre.setBackground(new java.awt.Color(255, 255, 255));
        txtnombrePadre.setForeground(new java.awt.Color(0, 0, 0));
        txtnombrePadre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Nombre Padre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtnombrePadre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrePadreActionPerformed(evt);
            }
        });
        txtnombrePadre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnombrePadreKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout containerRegistroLayout = new javax.swing.GroupLayout(containerRegistro);
        containerRegistro.setLayout(containerRegistroLayout);
        containerRegistroLayout.setHorizontalGroup(
            containerRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerRegistroLayout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre))
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTel)
                    .addComponent(boxCompañia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtnombreMadre))
                .addContainerGap())
            .addGroup(containerRegistroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(containerRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(containerActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(containerRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerRegistroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtnombrePadre)
                .addContainerGap())
        );
        containerRegistroLayout.setVerticalGroup(
            containerRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerRegistroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(containerRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtnombrePadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(txtnombreMadre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boxCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(containerRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(containerActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        containerbtnInicio.setBackground(new java.awt.Color(255, 255, 255));
        containerbtnInicio.setForeground(new java.awt.Color(255, 255, 255));

        btnInicioClient.setBackground(new java.awt.Color(255, 255, 255));
        btnInicioClient.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btnInicioClient.setForeground(new java.awt.Color(255, 255, 255));
        btnInicioClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha-atras (1).png"))); // NOI18N
        btnInicioClient.setContentAreaFilled(false);
        btnInicioClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInicioClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerbtnInicioLayout = new javax.swing.GroupLayout(containerbtnInicio);
        containerbtnInicio.setLayout(containerbtnInicioLayout);
        containerbtnInicioLayout.setHorizontalGroup(
            containerbtnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInicioClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        containerbtnInicioLayout.setVerticalGroup(
            containerbtnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerbtnInicioLayout.createSequentialGroup()
                .addComponent(btnInicioClient, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listado de Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jTableDatosClientes = new javax.swing.JTable(){
            public boolean isCellEditable (int rowIndex,int colIndex){
                return false;
            }
        };
        jTableDatosClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDatosClientes.setComponentPopupMenu(jPopupMenu1);
        jTableDatosClientes.setFocusable(false);
        jTableDatosClientes.getTableHeader().setResizingAllowed(false);
        jTableDatosClientes.getTableHeader().setReorderingAllowed(false);
        jTableDatosClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDatosClientesMouseClicked(evt);
            }
        });
        jTableDatosClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableDatosClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDatosClientes);

        txtBuscar.setBackground(new java.awt.Color(255, 255, 255));
        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        btnPorVencer.setForeground(new java.awt.Color(0, 0, 0));
        btnPorVencer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fecha-limite.png"))); // NOI18N
        btnPorVencer.setText("Por Vencer");
        btnPorVencer.setContentAreaFilled(false);
        btnPorVencer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPorVencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPorVencerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addComponent(btnPorVencer, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPorVencer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(containerbtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(containerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(containerbtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(containerRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioClientActionPerformed
    
     this.dispose();
    }//GEN-LAST:event_btnInicioClientActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       try {
          PreparedStatement ps = cn.prepareStatement("INSERT INTO clientes (alumno,nombre_apellido_padre,nombre_apellido_madre,numero_telefono,fecha_vencimiento,curso,monto) VALUES (?,?,?,?,?,?,?)");
          ps.setString(1, txtNombre.getText());
          ps.setString(2, txtnombrePadre.getText());
          ps.setString(3, txtnombreMadre.getText());
          ps.setString(4, txtTel.getText());
          ps.setString(5, txtFecha.getText());
          ps.setString(6, boxCompañia.getSelectedItem().toString());
          ps.setString(7, txtCuota.getText());
          ps.executeUpdate();
          JOptionPane.showMessageDialog(null,"DATOS GUARDADOS CORRECTAMENTE");
          mostrardatos();
          limpiarentradas();
       } catch(SQLException e){
           JOptionPane.showMessageDialog(null, "Cargue todos los campos");
           System.out.println("Error: "+e.getMessage());
       }
       txtNombre.requestFocus();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
      try{
          PreparedStatement ps= cn.prepareStatement("Update clientes set alumno='"+txtNombre.getText()+"',nombre_apellido_padre='"+txtnombrePadre.getText()+"',nombre_apellido_madre='"+txtnombreMadre.getText()+"',numero_telefono='"+txtTel.getText()+"',fecha_vencimiento='"+txtFecha.getText()+"',curso='"+boxCompañia.getSelectedItem()+"',monto='"+txtCuota.getText()+"' where id='"+txtId.getText()+"'");
           int indice = ps.executeUpdate();
           if (indice>0){
               JOptionPane.showMessageDialog(rootPane, "DATOS ACTUALIZADOS CORRECTAMENTE");
               mostrardatos();
               limpiarentradas();
           }
           else{
             JOptionPane.showMessageDialog(null, "No se selecciono niguna fila");
           }
      }catch(SQLException e){
          JOptionPane.showMessageDialog(null, "ERROR AL ACTUALIZAR DATOS");
          JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage());
      }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jTableDatosClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDatosClientesMouseClicked
        btnRegistrar.setEnabled(false);
        btnActualizar.setEnabled(true);
        int fila=this.jTableDatosClientes.getSelectedRow();
        this.txtId.setText(this.jTableDatosClientes.getValueAt(fila , 0).toString());
        this.txtNombre.setText(this.jTableDatosClientes.getValueAt(fila , 1).toString());
        this.txtnombrePadre.setText(this.jTableDatosClientes.getValueAt(fila , 2).toString());
        this.txtnombreMadre.setText(this.jTableDatosClientes.getValueAt(fila , 3).toString());
        this.txtTel.setText(this.jTableDatosClientes.getValueAt(fila ,4).toString());
        this.txtFecha.setText(this.jTableDatosClientes.getValueAt(fila , 5).toString());
        this.boxCompañia.setSelectedItem(this.jTableDatosClientes.getValueAt(fila , 6).toString());
        this.txtCuota.setText(this.jTableDatosClientes.getValueAt(fila , 7).toString());
    }//GEN-LAST:event_jTableDatosClientesMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       btnActualizar.setEnabled(false);
       btnRegistrar.setEnabled(true);
       limpiarentradas();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void containerRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_containerRegistroMouseClicked
       btnActualizar.setEnabled(false);
       btnRegistrar.setEnabled(true);
       limpiarentradas();
    }//GEN-LAST:event_containerRegistroMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
       btnActualizar.setEnabled(false);
       btnRegistrar.setEnabled(true);
       limpiarentradas();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
      if(JOptionPane.showConfirmDialog(null, "¿ESTA SEGURO DE ELIMINAR ALUMNO?","SALIR",JOptionPane.YES_NO_CANCEL_OPTION)==0);
            try{
                PreparedStatement ps= cn.prepareStatement("DELETE FROM clientes where ID='"+txtId.getText()+"'");
                int indice = ps.executeUpdate();
                if(indice>0){
                    mostrardatos();
                    limpiarentradas();
                }
                else{
                    System.out.println("No se selecciono ninguna fila");
                }
            }catch(SQLException e){
               JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage());
                System.out.println("Error: "+e.getMessage());
            }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
       if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
           txtnombrePadre.requestFocus();
       }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtTelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelKeyPressed
         if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
           txtFecha.requestFocus();
       }
    }//GEN-LAST:event_txtTelKeyPressed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
           boxCompañia.requestFocus();
        }
    }//GEN-LAST:event_txtFechaKeyPressed

    private void boxCompañiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_boxCompañiaKeyPressed
        if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
           btnRegistrar.requestFocus();
           btnRegistrar.doClick();
           
        }
    }//GEN-LAST:event_boxCompañiaKeyPressed

    private void jTableDatosClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDatosClientesKeyPressed
  
    }//GEN-LAST:event_jTableDatosClientesKeyPressed

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        String [] titulos = {"ID","Alumno/a","Nombre y Apellido Padre","Nombre y apellido Madre","Telefono","Fecha de Vencimiento","Curso","Monto Cuota"};
        String registros []= new String [50];
        String sql="select * from clientes WHERE alumno LIKE '%"+txtBuscar.getText()+"%'";
        
        model = new DefaultTableModel(null,titulos);
        
        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                registros[0]=rs.getString("ID");
                registros[1]=rs.getString("alumno");
                registros[2]=rs.getString("nombre_apellido_padre");
                registros[3]=rs.getString("nombre_apellido_madre");
                registros[4]=rs.getString("numero_telefono");
                registros[5]=rs.getString("fecha_vencimiento");
                registros[6]=rs.getString("curso");
                registros[7]=rs.getString("monto");
                model.addRow(registros);
            }
           jTableDatosClientes.setModel(model);
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al buscar: "+e);
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void btnPorVencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPorVencerActionPerformed
        PorVencer pv = new PorVencer();
        pv.setVisible(true);
    }//GEN-LAST:event_btnPorVencerActionPerformed

    private void txtnombreMadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreMadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreMadreActionPerformed

    private void txtnombreMadreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreMadreKeyPressed
         if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
           txtTel.requestFocus();
         }
    }//GEN-LAST:event_txtnombreMadreKeyPressed

    private void txtCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaActionPerformed

    private void txtCuotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuotaKeyPressed

    private void txtnombrePadreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrePadreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrePadreActionPerformed

    private void txtnombrePadreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrePadreKeyPressed
         if(evt.getExtendedKeyCode()==KeyEvent.VK_ENTER){
           txtnombreMadre.requestFocus();
         }
    }//GEN-LAST:event_txtnombrePadreKeyPressed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCompañia;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnInicioClient;
    private javax.swing.JButton btnPorVencer;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JPanel containerActualizar;
    private javax.swing.JPanel containerRegistrar;
    private javax.swing.JPanel containerRegistro;
    private javax.swing.JPanel containerbtnInicio;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatosClientes;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtnombreMadre;
    private javax.swing.JTextField txtnombrePadre;
    // End of variables declaration//GEN-END:variables

    private void mostrardatos() {
        DefaultTableModel modelo = new DefaultTableModel ();
        modelo.addColumn("ID");
        modelo.addColumn("Alumno/a");
        modelo.addColumn("Nombre Padre");
         modelo.addColumn("Nombre Madre");
        modelo.addColumn("Telefono");
        modelo.addColumn("Fecha de Vencimiento");
        modelo.addColumn("Curso");
        modelo.addColumn("Monto Cuota");
        jTableDatosClientes.setModel(modelo);
        String consultasql = "select*from clientes";
        String data[]=new String [8];
        
        Statement st;
        try {
         st=(Statement) cn.createStatement();
         ResultSet rs=st.executeQuery(consultasql);
            while (rs.next()) {                
                data[0]=rs.getString(1);
                data[1]=rs.getString(2);
                data[2]=rs.getString(3);
                data[3]=rs.getString(4);
                data[4]=rs.getString(5);
                data[5]=rs.getString(6);
                data[6]=rs.getString(7);
                data[7]=rs.getString(8);
                modelo.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage());
            
        }
    }
    private void limpiarentradas() {
        txtId.setText("");
        txtNombre.setText("");
        txtnombrePadre.setText("");
        txtnombreMadre.setText("");
        txtTel.setText("");
        txtFecha.setText("");
        boxCompañia.setSelectedIndex(0);
        txtCuota.setText("");
    }

   

    
}
